import random
import re

# Text provided by the user
lorem_text = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam interdum eu dolor nec elementum. Sed et mi quam. Vestibulum eget venenatis libero, quis facilisis metus. Curabitur bibendum orci condimentum, luctus lectus vitae, scelerisque augue. Nullam vitae quam semper diam posuere facilisis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi nisi eros, vestibulum et elementum ut, tincidunt convallis nunc.
Cras aliquam urna scelerisque mauris fermentum faucibus. Curabitur at vulputate nunc. Quisque sapien lorem, viverra et feugiat ultricies, ultrices at arcu. Donec a sapien gravida, scelerisque risus ac, ornare quam. Vestibulum arcu purus, tempor varius erat in, tempus porta lectus. Sed lobortis mi non sem lacinia auctor vel vel risus. Ut venenatis, felis non mattis pulvinar, dui orci tincidunt ligula, sed consectetur tellus nibh et nulla. Donec sit amet leo et tortor semper pharetra id a ipsum. Morbi nec aliquam orci. Sed commodo, ligula eu malesuada feugiat, quam magna aliquet nisi, interdum ornare velit odio ut velit.
Vestibulum id finibus neque. Maecenas scelerisque eget ante sed blandit. Curabitur et porttitor enim. Quisque efficitur, nunc id volutpat tristique, augue nibh cursus lorem, at finibus sem turpis quis nibh. Donec quis justo ac odio efficitur ornare. Cras mollis orci sed sem imperdiet finibus. Nullam feugiat, purus et mollis porttitor, massa purus maximus libero, non malesuada nulla tellus nec turpis. Vestibulum nec nunc ligula. Quisque ipsum odio, fringilla at euismod id, efficitur in odio.
Cras posuere sem elit, ac feugiat tellus feugiat vel. Sed metus enim, tincidunt sit amet efficitur nec, ullamcorper ut massa. Curabitur sagittis erat sapien, sed consectetur dui condimentum eget. Vivamus urna dolor, consectetur non elementum eget, feugiat non ex. Aenean fermentum, velit eget consectetur aliquet, velit erat ultricies nulla, at tincidunt nisl felis ut dolor. Ut vehicula turpis lectus, a ornare felis pulvinar at. Aenean ut leo nisi. Mauris consequat ipsum diam, eget condimentum lacus rhoncus vel. Morbi a tortor eu augue ultricies mollis sed at ipsum. Integer ac dignissim mi. Donec sed lorem eget lorem dictum pellentesque quis vel orci.
In efficitur tempor porta. Curabitur et lectus vel elit malesuada sagittis in at metus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed quis odio mauris. Praesent non laoreet dui. Suspendisse potenti. Pellentesque posuere, erat quis pretium rutrum, mauris nunc cursus sem, sollicitudin vehicula ligula nulla ut velit. Nullam ut purus at erat ullamcorper faucibus non vel enim. Curabitur quis orci metus. Donec purus orci, egestas scelerisque justo nec, egestas dapibus felis. Quisque ut lectus mattis, accumsan risus in, mollis sapien. Nunc elementum leo ex, quis sagittis lorem maximus venenatis. Fusce ut viverra lorem, ut pulvinar felis.
Vestibulum a lorem urna. Donec nec tortor sit amet tellus tristique dapibus ac sed ligula. Integer elit lectus, dignissim non tempor vitae, elementum nec felis. Integer tellus turpis, accumsan a fringilla ut, egestas nec erat. Pellentesque vel urna urna. Fusce vitae nisl mattis, varius lacus eget, hendrerit risus. Mauris ex dolor, faucibus et turpis non, rutrum dignissim est. Vestibulum velit velit, consequat cursus gravida vitae, tincidunt vel dui. Sed blandit metus sit amet tempor ullamcorper. Aenean eu tortor metus. Pellentesque faucibus viverra nunc, id suscipit ante fringilla quis. Nulla varius nulla urna, ut vulputate enim efficitur sed. Suspendisse vel blandit arcu. Donec congue tincidunt enim, quis lobortis est pellentesque vitae. Fusce vitae diam porta, lacinia odio vel, lacinia odio.
Nullam odio tortor, dictum vel ligula eget, fermentum euismod enim. Fusce interdum risus et nisi cursus dignissim. In efficitur magna magna, eu dapibus nulla egestas ullamcorper. Vestibulum aliquet sit amet urna non pellentesque. Quisque ullamcorper augue viverra, mollis eros vel, volutpat elit. Ut porttitor luctus est, ut cursus tellus imperdiet ut. Nam varius egestas urna, ultricies aliquam purus rutrum id. Mauris ac ipsum magna. Fusce consectetur blandit sem, sed pulvinar enim. Proin erat lectus, pretium at rutrum eu, pulvinar quis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras ut eros sapien. Ut vitae placerat nulla. Vestibulum dictum posuere volutpat. Maecenas malesuada lectus in ex tincidunt, id blandit leo commodo.
Pellentesque tincidunt justo a lorem vehicula, quis ornare mi fringilla. Integer eu iaculis ante, vel tincidunt lacus. Nunc tortor odio, scelerisque ac ultricies quis, luctus et nisl. Praesent dictum mattis dolor sed volutpat. Sed a justo ac lectus dignissim consequat non vel turpis. Nam pharetra quis diam in viverra. In in diam id metus pulvinar condimentum in suscipit risus. Sed bibendum quis nunc vitae eleifend. Curabitur in mi sed ex vestibulum auctor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam a diam maximus, finibus nisi ac, facilisis felis. Nullam in turpis eget quam cursus varius ac ac tellus. Donec bibendum tempus est, eu mollis metus rutrum ac. Quisque ut odio nisl. Phasellus sollicitudin nibh ornare, tristique metus a, imperdiet quam. Praesent porta ante dui, eget eleifend mi elementum ut.
Praesent elit ligula, vulputate et dui nec, congue scelerisque nulla. Aliquam maximus ligula eu urna consectetur pulvinar. Pellentesque eu quam a tellus mattis commodo. Duis ultrices dui eu justo sodales sagittis. Duis vitae laoreet purus. Vivamus blandit, ante nec laoreet facilisis, dui nisi faucibus nulla, vel tempus turpis metus quis ante. Phasellus mollis consectetur nisl non auctor. Curabitur sit amet dolor risus.
Phasellus consectetur justo nisl, sed finibus massa porttitor nec. Donec sagittis ipsum sit amet justo pretium, sit amet lobortis mauris pretium. In hac habitasse platea dictumst. Praesent magna est, faucibus vel consequat at, vulputate nec diam. Aliquam erat volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque eu tincidunt odio, eget volutpat elit. Maecenas ligula sapien, efficitur vel dui non, molestie iaculis dui. Praesent fermentum metus porta eros tempus varius. Nunc malesuada ullamcorper augue eget tincidunt. Donec feugiat pellentesque scelerisque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
Praesent lobortis, sapien ut mollis tincidunt, urna odio iaculis ante, eu iaculis massa neque quis ligula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec mollis quam eget erat tincidunt, pellentesque faucibus massa molestie. Sed sapien arcu, mattis sit amet tristique a, fringilla in tellus. In congue sem sit amet viverra porta. Etiam commodo, urna sit amet dignissim blandit, mauris dui imperdiet felis, at venenatis risus tortor quis mauris. Curabitur vehicula metus et ex eleifend molestie sed at eros. Fusce non nisl id metus viverra ullamcorper sit amet in quam. Suspendisse suscipit luctus vestibulum. Nunc blandit, tellus ac laoreet blandit, ipsum ligula varius arcu, eget hendrerit nisi eros vitae odio. Etiam fringilla urna sit amet lacinia convallis. Sed gravida fermentum mauris, et sagittis augue feugiat id. Vestibulum ultricies ex ligula, quis ultrices nibh viverra vel. Pellentesque rutrum tellus quis justo auctor, non vehicula elit pharetra. Pellentesque maximus venenatis neque, at suscipit nisi rhoncus vel.
Praesent a consectetur diam, ut accumsan ante. Phasellus nec sodales tellus, quis rhoncus nisl. Sed finibus massa libero, ut iaculis ex facilisis quis. Vivamus felis orci, ullamcorper nec pulvinar id, fringilla a libero. Suspendisse eget mi vitae eros hendrerit congue. Suspendisse potenti. Nunc aliquam ac purus non finibus. Phasellus nec turpis vel risus rutrum congue. Sed dapibus odio in pharetra commodo. Maecenas luctus massa vitae ornare hendrerit. Fusce sodales tincidunt diam at dignissim. Aliquam pharetra sagittis vehicula. Vivamus et tristique arcu. Cras urna magna, venenatis at magna sit amet, vestibulum sodales tortor. Morbi vehicula ante id mi congue, et feugiat dui blandit.
Proin molestie vestibulum nulla in lobortis. Nam lorem ligula, euismod sed mattis et, condimentum ac arcu. Sed facilisis libero ac orci consectetur, nec vestibulum mauris egestas. Duis in pellentesque magna. Vivamus ante enim, lacinia vitae sagittis non, molestie non turpis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus consequat lacinia turpis in fermentum. Vestibulum porttitor, dui id varius suscipit, lectus lacus tempus mauris, luctus rhoncus ante tellus et eros. Quisque ut sem velit. Etiam vitae diam ac libero venenatis porttitor. Duis aliquet, mi sit amet semper malesuada, sapien lacus vulputate justo, pellentesque sodales nulla tellus sit amet libero. Morbi tempor augue sit amet tellus lacinia cursus quis id nisi. Nulla egestas euismod orci non eleifend. Duis at tristique elit.
Nunc nunc tellus, convallis eget urna at, venenatis vehicula magna. Pellentesque sit amet eros enim. Phasellus viverra mollis nisi non semper. Pellentesque aliquet facilisis purus a bibendum. Quisque sit amet neque aliquet, placerat arcu a, eleifend leo. Fusce sodales imperdiet urna quis convallis. Ut bibendum justo et neque molestie, vel rutrum nisl sollicitudin. Donec quis fringilla dui. Morbi tempus finibus viverra.
Nulla vehicula felis sit amet lectus convallis pharetra. Cras semper placerat mauris nec tincidunt. Mauris non fringilla lacus. Integer feugiat scelerisque lorem sed volutpat. Suspendisse potenti. Donec laoreet rhoncus mollis. Ut sollicitudin neque sit amet lectus blandit, vitae congue justo sagittis. Nunc bibendum justo in justo condimentum dapibus. Suspendisse faucibus felis eu cursus efficitur. Sed nisi nibh, blandit non mollis et, porttitor non ligula. Mauris nunc ante, sollicitudin at elit nec, dignissim sodales tortor.
Vestibulum commodo iaculis vulputate. Vestibulum accumsan est vel ligula convallis, ac faucibus lacus facilisis. Suspendisse dapibus eleifend convallis. Donec dictum consectetur libero. Aenean eget quam non libero porttitor scelerisque. Proin euismod leo quis rutrum efficitur. Pellentesque porttitor lacus purus, sit amet semper sapien auctor ut. Vestibulum facilisis neque at fermentum sollicitudin. Aenean risus sem, semper eget maximus at, pharetra sed nisi. Pellentesque eu augue finibus, consectetur diam ut, porttitor augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum non iaculis turpis. Vivamus ac accumsan orci. Nam ut tristique neque, a varius nunc. Aenean eu enim ante. Maecenas efficitur nisi interdum massa aliquam ornare.
Aenean eu varius mauris. Vivamus nec vehicula ipsum, sed posuere tellus. Duis tempus scelerisque ante, quis aliquam risus vehicula eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec consectetur rutrum lorem, at commodo ipsum ultrices non. Curabitur lobortis, risus id egestas euismod, neque diam iaculis sapien, a semper enim augue sed velit. Sed a erat at tellus gravida tempor. Etiam semper consequat laoreet. Donec gravida pulvinar dolor nec viverra. Suspendisse a egestas quam. Proin quis lorem efficitur, hendrerit ex vitae, ullamcorper risus. Suspendisse odio lorem, aliquet non turpis vel, tincidunt ullamcorper ex. Duis vitae sollicitudin nibh, at dignissim augue. Nunc sed consectetur sapien.
Suspendisse id sollicitudin felis, a sodales magna. Fusce vitae mauris non nisl lobortis facilisis. Cras volutpat maximus tellus, pulvinar pellentesque risus commodo egestas. Proin nec ante sit amet leo ullamcorper scelerisque ut a arcu. Phasellus vel ullamcorper sem. Vestibulum tempus feugiat risus, sit amet ultrices turpis accumsan at. Etiam ac arcu sit amet sapien imperdiet commodo malesuada tempor neque. Proin a ultricies urna. Fusce vel nisi tempor, pulvinar orci vel, pretium magna. Donec sit amet ligula in arcu faucibus iaculis ut eu velit. Quisque sem purus, tristique a vulputate ac, sodales quis leo.
Aliquam non lorem maximus, placerat lectus a, convallis nisl. Donec id tincidunt nibh. Curabitur id sagittis nisi. Nunc lacinia arcu quis sem elementum ullamcorper. Mauris condimentum id lectus ac fermentum. Suspendisse vehicula, mauris at egestas fermentum, ipsum ante cursus erat, sed laoreet dui orci pellentesque neque. Sed sed mauris ac lacus vestibulum porta. Morbi sodales, sapien in scelerisque pellentesque, diam dolor sollicitudin dolor, vel mattis velit libero a enim. Sed rhoncus in nisi dictum rhoncus. Nunc et urna scelerisque nisl bibendum ornare in ac lorem. Praesent fermentum lorem in lacus mollis hendrerit.
Morbi sagittis lacus non tempor sagittis. Cras porta dui magna, in vulputate ante laoreet pellentesque. Integer consectetur non turpis ut auctor. Proin id magna vitae lorem viverra facilisis. Nulla non orci erat. Pellentesque posuere, quam sed egestas interdum, enim urna blandit dolor, eget varius nisl lorem in massa. Mauris pretium augue suscipit tortor ultricies, a sollicitudin orci ultricies. Mauris vel sem eget orci fringilla ornare. Nam condimentum vehicula lacinia. Integer et egestas sem. Maecenas sit amet est at arcu accumsan venenatis eu et justo. Sed tincidunt arcu at tellus condimentum efficitur. Sed quam quam, sollicitudin ut dapibus non, tempus et mi. Nullam sem mi, sodales a dignissim sit amet, consectetur sit amet enim. Etiam tristique mi non elit placerat, vitae pharetra sapien egestas.
Phasellus nulla nulla, ultrices ut luctus id, iaculis id lectus. Maecenas ut sagittis nunc. Ut viverra lacus ut enim venenatis facilisis sit amet nec lectus. Praesent sodales porttitor turpis. Pellentesque orci nulla, eleifend in diam sed, egestas consequat nisl. Nulla magna nunc, facilisis vitae tempus a, tincidunt id justo. Morbi dictum lectus et neque blandit dapibus. Nulla consectetur molestie consectetur. Sed porta felis sed lorem fermentum ornare. Suspendisse pellentesque consectetur nulla vel aliquam. Suspendisse potenti. Duis sollicitudin rhoncus enim, sed consequat tortor malesuada eu. Donec consequat laoreet ligula, non ultricies mi euismod eget.
Morbi consequat mi nunc, sit amet tempus ligula faucibus eu. Cras suscipit dapibus quam, ac convallis dolor interdum ac. Quisque in urna nisi. In at eleifend sapien. Integer nec vulputate orci. Ut ut nisi nec erat cursus eleifend. Nullam vulputate ac leo eu suscipit.
Nam interdum felis a nisl maximus, a porttitor mi congue. In malesuada, tellus a varius volutpat, mauris risus commodo nisi, ut dictum ante augue a ex. Suspendisse pharetra et purus a dictum. Aliquam luctus, nibh non aliquam semper, lacus magna venenatis lorem, non malesuada mauris ante vitae lectus. Suspendisse tincidunt neque neque, nec egestas magna convallis non. Quisque sit amet mattis ligula, eget vulputate ante. Nam accumsan eros sit amet arcu laoreet, et rutrum leo congue. Donec iaculis venenatis vehicula. Integer non velit viverra, lobortis nunc quis, pharetra felis. Vivamus non lectus mattis, pretium nisi nec, accumsan nisi. Aliquam et purus massa.
Sed fringilla imperdiet ex in pellentesque. Fusce urna ex, porttitor sit amet pretium nec, eleifend commodo erat. Integer nec augue eget risus cursus dictum quis elementum ex. Nulla ornare ante eget mauris lobortis, at maximus tortor scelerisque. Donec nisl erat, volutpat quis sodales pulvinar, malesuada aliquet nisl. Quisque a sem a nulla ultricies vulputate. Sed pellentesque non neque in rhoncus. Duis non neque dapibus, imperdiet libero ut, luctus sem. Ut metus leo, egestas eget massa eu, ultricies fringilla turpis. In vitae dui at metus lobortis viverra. Phasellus quis magna ac quam feugiat laoreet tempor in dolor. Ut lacinia, dui vitae suscipit suscipit, augue libero posuere elit, eu facilisis nulla nibh eu leo.
Nunc quam nisl, ornare eget justo nec, mollis aliquet libero. Mauris sed magna nec ex efficitur consectetur vitae vitae eros. Pellentesque lacinia venenatis commodo. Pellentesque aliquet orci id urna egestas commodo. Phasellus iaculis, tortor ac cursus finibus, quam diam interdum ipsum, in lacinia massa ligula ut leo. Aliquam pulvinar felis urna, eu luctus felis gravida vel. Etiam vel molestie augue, a lobortis lectus. Integer vestibulum lectus gravida, eleifend augue vitae, finibus turpis. Cras non lobortis odio, mattis porttitor risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur nec odio semper, ullamcorper tortor eu, ullamcorper velit. Integer id pellentesque mauris. In hac habitasse platea dictumst. Nunc eu metus nec sem malesuada dapibus a ut mauris.
"""

# Extract individual words, clean punctuation, convert to lowercase
words = re.findall(r'\b[a-zA-Z]+\b', lorem_text.lower())
# Unique word list to maximize variety
words = list(set(words))

file_path = "insert_10m_lorem_todos.sql"
batch_size = 10000
total_rows = 10000000

# To guarantee lightning-fast generations, we will utilize random choices efficiently
print("Writing 10 million random lorem phrases into optimized PostgreSQL batches...")

with open(file_path, "w", encoding="utf-8") as f:
    f.write("BEGIN;\n")
    
    for i in range(0, total_rows, batch_size):
        values = []
        for _ in range(batch_size):
            # Pick a length between 1 and 4 words
            length = random.randint(1, 4)
            chosen = random.choices(words, k=length)
            
            # Form phrase and capitalize first letter
            phrase = " ".join(chosen).capitalize()
            # Escape single quotes (PostgreSQL standard)
            safe_phrase = phrase.replace("'", "''")
            
            # Pick a random status between 1 and 6
            status = random.randint(1, 6)
            
            values.append(f"('{safe_phrase}', {status})")
        
        # Write batch chunk
        f.write(f'INSERT INTO "public"."todos" ("title", "status") VALUES\n' + ",\n".join(values) + ";\n")
        
    f.write("COMMIT;\n")

print("Finished generating file successfully.")